--- 

- name: garantindo pacotes basicos 
  hosts: all 
  tasks: 
   - name: instalando pacotes
     apt:
      name:  "{{ item }}"
      state: present 
     with_items: 
      - vim 
      - nano
      - sl 
      - ccze 
      - dnsutils 
