---
# tasks file for pacotes

- name: instalando pacotes 
  package: 
   name: "{{ item }}"
   state: present
  with_items: 
   - vim 
   - nano 
   - sl 
   - cowsay 

- name: instalando o epel-release 
  package: 
   name: epel-release 
  when: ansible_os_family == "RedHat" 


